## Question 2

In [1]:
import torch
from torch import Tensor
import numpy as np
import math

X_i = torch.tensor([[ 0.12, -0.87,  0.33,  0.45],
                    [ 0.76,  0.21, -0.34,  0.67],
                    [-0.55,  0.18,  0.29, -0.73],
                    [ 0.03, -0.99,  0.42,  0.11],
                    [ 0.76,  0.21, -0.34,  0.67],
                    [-0.31,  0.66, -0.74,  0.09],
                    [-0.92,  0.37,  0.28, -0.50]])

W_Q = torch.tensor([[ 0.12, -0.87,  0.33,  0.45],
                    [ 0.76,  0.21, -0.34,  0.67],
                    [-0.55,  0.18,  0.29, -0.73],
                    [ 0.03, -0.99,  0.42,  0.11]])

W_K = torch.tensor([[ 0.64, -0.27,  0.89, -0.12],
                    [-0.45,  0.33,  0.71,  0.08],
                    [ 0.19, -0.94,  0.56,  0.37],
                    [ 0.03,  0.85, -0.41,  0.76]])

W_V = torch.tensor([[ 0.58, -0.13,  0.94,  0.22 ],
                    [-0.31,  0.66, -0.74,  0.09],
                    [ 0.45,  0.11, -0.88,  0.67],
                    [-0.92,  0.37,  0.28, -0.50]])

Q = torch.matmul(X_i, W_Q)
K = torch.matmul(X_i, W_K)
V = torch.matmul(X_i, W_V)

def scaled_dot_product_attention(Q: Tensor, K: Tensor, V: Tensor, d: int):
    scaling_factor = 1 / math.sqrt(d)

    attn_weight = torch.matmul(Q, K.T) * scaling_factor
    attn_weight = torch.softmax(attn_weight, dim=1)
    return torch.matmul(attn_weight, V)

print(scaled_dot_product_attention(Q, K, V, 4))

tensor([[-0.0278,  0.0325, -0.3108,  0.0412],
        [ 0.0488, -0.1117,  0.0405,  0.0265],
        [-0.2811,  0.1322,  0.1575, -0.2035],
        [-0.0825,  0.0691, -0.2955,  0.0031],
        [ 0.0488, -0.1117,  0.0405,  0.0265],
        [-0.0947, -0.0424,  0.3061, -0.1067],
        [-0.2932,  0.1361,  0.1879, -0.2166]])


In [4]:
W_Q_1, W_Q_2 = torch.chunk(W_Q, 2, dim=1)
W_K_1, W_K_2 = torch.chunk(W_K, 2, dim=1)
W_V_1, W_V_2 = torch.chunk(W_V, 2, dim=1)

head_1 = scaled_dot_product_attention(X_i @ W_Q_1, X_i @ W_K_1, X_i @ W_V_1, 2)
head_2 = scaled_dot_product_attention(X_i @ W_Q_2, X_i @ W_K_2, X_i @ W_V_2, 2)

print(head_1)
print(head_2)

tensor([[-0.0052,  0.0082],
        [ 0.1272, -0.1640],
        [-0.3544,  0.1830],
        [-0.0876,  0.0620],
        [ 0.1272, -0.1640],
        [-0.1071, -0.0197],
        [-0.3686,  0.1901]])
tensor([[-0.0302, -0.0556],
        [ 0.1970, -0.1066],
        [-0.0299, -0.0477],
        [-0.0742, -0.0441],
        [ 0.1970, -0.1066],
        [ 0.1544, -0.0830],
        [-0.0332, -0.0460]])
